// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// MarginalLikelihood_cpp
double MarginalLikelihood_cpp(const arma::mat& Y, const Rcpp::IntegerVector& cluster_assign, const Rcpp::IntegerVector& team_assign, int k, int j, double sigmasq_mu, const arma::mat& Sigma);
RcppExport SEXP _DP_RST_MarginalLikelihood_cpp(SEXP YSEXP, SEXP cluster_assignSEXP, SEXP team_assignSEXP, SEXP kSEXP, SEXP jSEXP, SEXP sigmasq_muSEXP, SEXP SigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type cluster_assign(cluster_assignSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type team_assign(team_assignSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type j(jSEXP);
    Rcpp::traits::input_parameter< double >::type sigmasq_mu(sigmasq_muSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Sigma(SigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(MarginalLikelihood_cpp(Y, cluster_assign, team_assign, k, j, sigmasq_mu, Sigma));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_DP_RST_MarginalLikelihood_cpp", (DL_FUNC) &_DP_RST_MarginalLikelihood_cpp, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_DP_RST(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
