# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

MarginalLikelihood_cpp <- function(Y, cluster_assign, team_assign, k, j, sigmasq_mu, Sigma) {
    .Call(`_DP_RST_MarginalLikelihood_cpp`, Y, cluster_assign, team_assign, k, j, sigmasq_mu, Sigma)
}

